package trinity.db.mysql;

public enum SQLConnectResult 
{
	RESULT_OK,
	RESULT_MYSQL_OK,
	RESULT_MARIADB_OK,
	RESULT_BADCLASS,
	RESULT_CREDENTIALERROR,
	RESULT_DBACCESSDENIED,
	RESULT_CONNECTERR,
	RESULT_SQLEXCEPTION,
	RESULT_OTHEREXCEPTION
}
